[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = []

[dependencies]
anyhow = "1.0.78"
colored = "2.1.0"
itertools = "0.12.0"
num-traits = "0.2.17"
rand = "0.8.5"
thiserror = "1.0.53"
